---
title: "WDV MSA"
author: "Maciej Motyka"
date: "4/8/2020"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    code_folding: "hide"
    # theme: darkly
    #css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# aBayesQR trees
```{r fig.height=10, fig.width=15}
drake::loadd("nj_mlDist_ClustO_abqr_001", "nj_mlDist_ClustW_abqr_001", "nj_mlDist_Muscl_abqr_001")
par(mfrow = c(1,3))
ape::plot.phylo(nj_mlDist_ClustO_abqr_001, main = "ClustalO -> dist.ml -> NJ", use.edge.length = F, cex = 1.3)
ape::plot.phylo(nj_mlDist_ClustW_abqr_001, main = "ClustalW -> dist.ml -> NJ", use.edge.length = F, cex = 1.3)
ape::plot.phylo(nj_mlDist_Muscl_abqr_001, main = "Muscle -> dist.ml -> NJ", use.edge.length = F, cex = 1.3)
```
 
```{r fig.height=10, fig.keep='all', fig.show='hold'}
rm(list = ls())
# drake::loadd("nj_mlDist_ClustO_abqr_001",
#              "nj_mlDist_ClustW_abqr_001",
#              "nj_mlDist_Muscl_abqr_001")
trees <- c("nj_mlDist_ClustO_abqr_001",
             "nj_mlDist_ClustW_abqr_001",
             "nj_mlDist_Muscl_abqr_001")
drake::loadd(list = !!! rlang::syms(trees[]))
drake::loadd(list = as.symbol(c("nj_mlDist_ClustO_abqr_001", "nj_mlDist_ClustW_abqr_001")))
ls()

syms <- list(nj_mlDist_ClustO_abqr_001,
              nj_mlDist_ClustW_abqr_001,
              nj_mlDist_Muscl_abqr_001)

rooted_trees <- lapply(X = trees,
                       FUN = ape::root.phylo,
                       outgroup = "s05_h1_57",
                       resolve.root = T)

treespace::plotTreeDiff(tr1 = rooted_trees[[1]],
                       tr2 = rooted_trees[[2]],
                       use.edge.length = FALSE,
                       treesFacing = TRUE,
                       colourMethod = "palette",
                       palette = adegenet::funky,
                       tipMatch = FALSE) # defaults to TRUE; disable when using ladderized treesD

treespace::plotTreeDiff(tr1 = rooted_trees[[1]],
                       tr2 = rooted_trees[[3]],
                       use.edge.length = FALSE,
                       treesFacing = TRUE,
                       colourMethod = "palette",
                       palette = adegenet::funky,
                       tipMatch = FALSE) # defaults to TRUE; disable when using ladderized trees
```

```{r fig.height=15, fig.width=12}
rm(list = ls())
# drake::loadd("nj_mlDist_ClustO_abqr_001", "nj_mlDist_ClustW_abqr_001", "nj_mlDist_Muscl_abqr_001")
# trees <- Hmisc::llist(nj_mlDist_ClustO_abqr_001,
#            nj_mlDist_ClustW_abqr_001,
#            nj_mlDist_Muscl_abqr_001)
trees <- c("nj_mlDist_ClustO_abqr_001",
           "nj_mlDist_ClustW_abqr_001",
           "nj_mlDist_Muscl_abqr_001")
drake::loadd(trees[])
ls()

# trees <- c(c(nj_mlDist_ClustO_abqr_001,
#              nj_mlDist_ClustW_abqr_001,
#              nj_mlDist_Muscl_abqr_001))

tr2 <- as.vector(trees,)
tr2

phangorn::densiTree(tr2,
                   type = "p",
                   scaleX = T,
                   # jitter = list(amount = 0.05, random = FALSE),
                   alpha = 0.5,
                   col = c("red", "green", "blue"),
                   use.edge.length = T
                   )
```


## Heatmap
#```{r}
#drake::loadd(abqr_001_trspc)
#adegraphics::table.image(abqr_001_trspc$D)
#```

```{r session_info, include=TRUE, echo=TRUE, results='markup'}
sessioninfo::session_info()
```